### PR TITLE
Roi calculator

### PR DESCRIPTION
**Pull request by mohit2530**
@sujan-dahal i took some of your css changes.

I also added a feature call roi calculator. that calculates how much the user can save.

prettifying the other aspects of the application.

### CODE REVIEW

**Comment by mohit2530** [comment]
Screen Shot 2022-12-11 at 8 45 14 PM

**Comment by sujan-dahal** [comment]
center the item, missing proper validation for all form fields. roi calculator doesn't save that is the correct way. missing icons for textfields for the calc.

**Comment by sujan-dahal** [comment]
fix the flexbox issue too. should be center and nice.

**Comment by mohit2530** [comment]
> fix the flexbox issue too. should be center and nice.

setting the container to the middle of the screen.

**Comment by mohit2530** [comment]
Screen Shot 2022-12-12 at 8 17 17 AM

**Comment by mohit2530** [comment]
Large form factor -
Screen Shot 2022-12-13 at 6 24 10 AM

Medium form factor - 

Screen Shot 2022-12-13 at 6 24 40 AM


Small form factor - 
Screen Shot 2022-12-13 at 6 25 22 AM

**Pull request closed without merging**
